### ISSUE TITLE
Auswahl in tl_module möglich?

### ISSUE THREAD

**Issue by ideefixx** [Sioweb/SWLoadForDevice#1]
Wäre es denkbar die Auswahl auch für tl_module zu implementieren?

**Comment by Sioweb** [comment]
Ho! Ja

Ich hab hier auf Github eben das Modul mal dafür vorbereitet.
Kannst du das für mich testen? Ich hab grade nicht sonderlich viel Zeit o:

**Comment by ideefixx** [comment]
ich habe im Moment leider auch nicht soviel zeit, es aber kurz getestet. Läuft derzeit leider auf einen Fehler:

#0 [internal function]: __error(2, 'in_array() expe...', '/homepages/40/d...', 160, Array)
#1 /XXX/system/modules/core/library/Contao/System.php(160): in_array('getInstance', NULL)
#2 /XXX/system/modules/core/library/Contao/Controller.php(483): Contao\System::importStatic('ContentDevice')
#3 /XXX/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#4 /XXX/system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#5 /XXX/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#6 /XXX/system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#7 /XXX/system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#8 /XXX/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#9 /XXX/system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#10 /XXX/index.php(20): Contao\FrontendIndex->run()
#11 {main}

**Comment by Sioweb** [comment]
Danke. Ich schau es mir nochmal in ruhe an.

**Comment by Sioweb** [comment]
So, sollte behoben sein. Die aktuelle Version kann heruntergeladen werden. Die Option gilt nur für Module, die nicht mit dem Inhaltselement geladen werden.

**Comment by ideefixx** [comment]
kann ich bestätigen, danke für die Umsetzung.
